# Generated by Django 3.2.2 on 2021-05-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20, verbose_name='用户名')),
                ('upass', models.CharField(max_length=50, verbose_name='密码')),
                ('uemail', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('uphone', models.CharField(max_length=20, null=True, verbose_name='手机号')),
                ('isActive', models.BooleanField(default=True, verbose_name='启用状态')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'index_users',
            },
        ),
    ]
