# Generated by Django 3.1 on 2021-04-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='index_users',
        ),
    ]
