# Generated by Django 3.1 on 2021-04-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210426_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uemail',
            field=models.EmailField(max_length=254, null=True, verbose_name='邮箱'),
        ),
    ]
